#!/usr/bin/env node
/**
 * The entire build. There is no bundler and no framework — `public/` is the
 * site, exactly as it ships. This script does the two jobs that genuinely
 * cannot be done by hand without going stale:
 *
 *   1. Propagates the canonical origin. `SITE_ORIGIN` in wrangler.jsonc is the
 *      single place you set your domain; it is rewritten into every canonical
 *      URL, Open Graph tag, sitemap entry and robots.txt line.
 *
 *   2. Regenerates public/_headers, including the SHA-256 hashes of every
 *      inline <script> and <style> block. Those hashes are what let the
 *      Content-Security-Policy drop 'unsafe-inline' — the single highest-value
 *      header on a page that takes user input.
 *
 * Idempotent. Run it as often as you like; `npm run deploy` runs it for you.
 */
import { createHash } from "node:crypto";
import { readFile, writeFile, readdir } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC_DIR = join(ROOT, "public");

/** The origin the files were authored with. Only used if the canonical tag is missing. */
const SEED_ORIGIN = "https://unassumed.com";

/** Files whose text may contain the origin. */
const TEXT_EXTENSIONS = new Set([".html", ".txt", ".xml", ".webmanifest", ".json", ".css", ".js"]);

/* ── jsonc ───────────────────────────────────────────────────────────────── */

/**
 * Strips `//` and block comments from JSONC without touching comment-like
 * sequences inside string literals — which every URL in the file contains.
 */
function stripJsonComments(input) {
  let out = "";
  let inString = false;
  let inLine = false;
  let inBlock = false;

  for (let i = 0; i < input.length; i += 1) {
    const ch = input[i];
    const next = input[i + 1];

    if (inLine) {
      if (ch === "\n") { inLine = false; out += ch; }
      continue;
    }
    if (inBlock) {
      if (ch === "*" && next === "/") { inBlock = false; i += 1; }
      continue;
    }
    if (inString) {
      out += ch;
      if (ch === "\\") { out += next ?? ""; i += 1; }
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') { inString = true; out += ch; continue; }
    if (ch === "/" && next === "/") { inLine = true; i += 1; continue; }
    if (ch === "/" && next === "*") { inBlock = true; i += 1; continue; }
    out += ch;
  }
  // Trailing commas are legal in wrangler.jsonc but not in JSON.parse.
  return out.replace(/,(\s*[}\]])/g, "$1");
}

/* ── Content-Security-Policy ─────────────────────────────────────────────── */

function sha256Base64(source) {
  return createHash("sha256").update(source, "utf8").digest("base64");
}

/** Collects hashes for inline <script> and <style> across every HTML file. */
async function collectInlineHashes(files) {
  const scripts = new Set();
  const styles = new Set();

  for (const file of files.filter((f) => f.endsWith(".html"))) {
    const html = await readFile(join(PUBLIC_DIR, file), "utf8");

    for (const [, body] of html.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) {
      if (body.trim()) scripts.add(`'sha256-${sha256Base64(body)}'`);
    }
    for (const [, body] of html.matchAll(/<style\b[^>]*>([\s\S]*?)<\/style>/gi)) {
      if (body.trim()) styles.add(`'sha256-${sha256Base64(body)}'`);
    }
  }
  return { scripts: [...scripts], styles: [...styles] };
}

function buildCsp({ scripts, styles }) {
  return [
    "default-src 'self'",
    `script-src 'self'${scripts.length ? " " + scripts.join(" ") : ""}`,
    `style-src 'self'${styles.length ? " " + styles.join(" ") : ""}`,
    "img-src 'self' data:",
    "font-src 'self'",
    // The waitlist POST goes to this origin and nowhere else.
    "connect-src 'self'",
    "form-action 'self'",
    "frame-src 'none'",
    "object-src 'none'",
    "media-src 'none'",
    "worker-src 'none'",
    "manifest-src 'self'",
    "base-uri 'none'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}

function buildHeaders(csp) {
  return `# GENERATED BY scripts/build.mjs — DO NOT EDIT BY HAND.
# Edit scripts/build.mjs and run \`npm run build\`.
#
# These apply to static assets only. Responses generated by the Worker set
# their own headers in src/security.ts.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Permissions-Policy: accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(self), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), xr-spatial-tracking=(), interest-cohort=()

# Fonts never change under these filenames — a new subset gets a new name.
/fonts/*
  Cache-Control: public, max-age=31536000, immutable
  Cross-Origin-Resource-Policy: same-origin

# Stylesheet and script are not content-hashed, so they cannot be immutable.
# Ten minutes of edge staleness after a deploy, then a week of serving the old
# copy while the new one is fetched in the background.
/styles.css
  Cache-Control: public, max-age=600, stale-while-revalidate=604800
/app.js
  Cache-Control: public, max-age=600, stale-while-revalidate=604800

# The social card and the icons are fetched by other origins' documents and by
# crawlers, so they must not be restricted to same-origin.
/og.png
  Cache-Control: public, max-age=604800
  Cross-Origin-Resource-Policy: cross-origin
/icon-*.png
  Cache-Control: public, max-age=604800
  Cross-Origin-Resource-Policy: cross-origin
/apple-touch-icon.png
  Cache-Control: public, max-age=604800
  Cross-Origin-Resource-Policy: cross-origin
/favicon.*
  Cache-Control: public, max-age=604800
  Cross-Origin-Resource-Policy: cross-origin

# Never let a stale landing page or a stale robots/sitemap sit in a CDN.
/
  Cache-Control: public, max-age=0, must-revalidate
/*.html
  Cache-Control: public, max-age=0, must-revalidate
/robots.txt
  Cache-Control: public, max-age=3600
/sitemap.xml
  Cache-Control: public, max-age=3600
/llms.txt
  Cache-Control: public, max-age=3600
`;
}

/* ── main ────────────────────────────────────────────────────────────────── */

async function listPublicFiles(dir = PUBLIC_DIR, prefix = "") {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) files.push(...(await listPublicFiles(join(dir, entry.name), rel)));
    else files.push(rel);
  }
  return files;
}

async function main() {
  const wranglerSource = await readFile(join(ROOT, "wrangler.jsonc"), "utf8");
  const wrangler = JSON.parse(stripJsonComments(wranglerSource));
  const origin = wrangler?.vars?.SITE_ORIGIN;

  if (typeof origin !== "string" || !/^https?:\/\/[^/\s]+$/.test(origin)) {
    throw new Error(
      `vars.SITE_ORIGIN in wrangler.jsonc must be an origin with no path or trailing slash. Got: ${JSON.stringify(origin)}`,
    );
  }

  // The origin currently baked into the files, read from the canonical tag on
  // the landing page. Deriving it from the files themselves — rather than from
  // a state file that may not have been committed — means this is correct on a
  // fresh clone and after any number of domain changes.
  const indexHtml = await readFile(join(PUBLIC_DIR, "index.html"), "utf8");
  const canonical = /<link\s+rel="canonical"\s+href="(https?:\/\/[^/"]+)/.exec(indexHtml);
  const previous = canonical?.[1] ?? SEED_ORIGIN;

  const files = await listPublicFiles();
  let rewritten = 0;

  if (previous !== origin) {
    for (const file of files) {
      const ext = file.slice(file.lastIndexOf("."));
      if (!TEXT_EXTENSIONS.has(ext)) continue;

      const path = join(PUBLIC_DIR, file);
      const before = await readFile(path, "utf8");
      const after = before.split(previous).join(origin);
      if (after !== before) {
        await writeFile(path, after);
        rewritten += 1;
      }
    }
  }

  const hashes = await collectInlineHashes(files);
  const csp = buildCsp(hashes);
  await writeFile(join(PUBLIC_DIR, "_headers"), buildHeaders(csp));

  console.log(`origin      ${origin}${previous !== origin ? `  (was ${previous}, rewrote ${rewritten} files)` : ""}`);
  console.log(`csp hashes  ${hashes.scripts.length} script, ${hashes.styles.length} style`);
  console.log("wrote       public/_headers");

  if (origin === SEED_ORIGIN) {
    console.warn(
      `\n  ⚠  SITE_ORIGIN is still the placeholder ${SEED_ORIGIN}.\n     Set your real domain in wrangler.jsonc and run this again before deploying.\n`,
    );
  }
}

main().catch((error) => {
  console.error(`build failed: ${error.message}`);
  process.exitCode = 1;
});
